apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: add-component-template
  title: Onboard your component to RHDH
  description: Create and register a new component to RHDH Catalog
  tags:
    - bonus
    - rhone
spec:
  owner: rhdh
  type: service
  parameters:
    - title: Provide new component details
      required:
        - component_id
      properties:
        # Add form parameters here
    - title: Application repository Information
      required:
        - repo
      properties:
        repo:
          title: Repository Location
          type: object
          properties:
            host:
              title: Repo Host
              type: string
              description: Your SCM host
              default: {{ gitlab_host }}
              enum:
                - {{ gitlab_host }}
            owner:
              title: Repo Owner
              type: string
              description: Your SCM host organization/group
              default: {{ gitlab_destination_group }}
              enum:
                - {{ gitlab_destination_group }}
  steps:
    - id: template
      name: Fetch Skeleton + Template
      action: fetch:template
      input:
        url: ./skeleton
        copyWithoutTemplating:
          - .github/workflows/*
        values:
          component_id: {{ '${{ parameters.component_id }}' }}
          description: {{ '${{ parameters.description }}' }}
          owner: {{ '${{ user.entity.metadata.name }}' }}
          host: {{ '${{ parameters.repo.host }}' }}
          destination: {{ '${{ parameters.repo.owner }}' }}/{{ '${{ parameters.component_id }}' }}
          
    - id: publish
      name: Publish
      action: publish:gitlab
      input:
        repoUrl: "{{ '${{ parameters.repo.host }}' }}?owner={{ '${{ parameters.repo.owner }}' }}&repo={{ '${{parameters.component_id}}' }}"
        repoVisibility: public

    - id: register
      name: Register
      action: catalog:register
      input:
        # repoContentsUrl: {{ '${{ steps.publish.output.REPLACE_ME }}' }}
        catalogInfoPath: "/catalog-info.yaml"
  
  output:
    links:
      - title: Source Code Repository
        url: {{ '${{ steps.publish.output.remoteUrl }}' }}
      - title: Open Component in catalog
        icon: catalog
        #entityRef: {{ '${{ steps.register.output.REPLACE_ME }}' }}